  # Site settings
  title: NOK8
  SEOTitle: 我的博客 | My Blog
  header-img: img/post-bg-desk.jpg
  email: NULL
  description: "NULL"
  keyword: "NULL"
  url: "http://NOK8.github.io"          # name改成你的ID
  baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
  github_repo: "https://github.com/NOK8/NOK8.github.io.git" #

  # Sidebar settings
  sidebar: true                           # whether or not using Sidebar.
  sidebar-about-description: "NULL"
  #sidebar-avatar: /img/avatar_binggan.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`

  # SNS settings
  RSS: false
  # weibo_username: 暂无
  #zhihu_username:     暂无
  #github_username:    暂无
  #facebook_username:  暂无
  #jianshu_username:   暂无
  #twitter_username: 暂无